language: 'python'

branches:
  only:
    - master

python:
  - '2.7'

# The SSH references to submodules could cause some problems. We will 
# change the ssh directions to http.
git:
  submodules: false

install:
  - pwd
  - pip install coveralls
  - cd scripts/
  - bash ./setup.sh -t

script:
  - coverage run test_clientToServer.py

after_success:
  - cd ../../
  - 'coveralls'
