sudo: false

language: 'python'

branches:
  only:
    - master

python:
  - '2.7'

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd protocol
  - git checkout jrpc_if
  - cd ../ 

install:
  - pip install coveralls coverage nose
  - cd scripts/
  - bash ./setup.sh -travisCI
  - cd ../tests
  - mkdir build && cd build
  - wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.zip
  - unzip sip-4.17.zip && cd sip-4.17
  - python configure.py --incdir="/home/travis/virtualenv/python2.7.9/lib/python2.7"
  - make
  - make install
  - cd ../ && rm -r -f sip-4.17
  - wget http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz
  - tar xvzf PyQt-x11-gpl-4.11.4.tar.gz
  - cd PyQt-x11-gpl-4.11.4
  - python ./configure.py --confirm-license --no-designer-plugin --no-tools --no-qsci-api --no-python-dbus -q /usr/bin/qmake-qt4 -e QtGui -e QtCore
  - make
  - make install
  - cd ../ && rm -r -f PyQt-x11-gpl-4.11.4 && cd ../

script:
#  - python setup.py install
  - nosetests --with-coverage --cover-erase --cover-package=ampauth
#  - coverage run test_clientToServer.py
#  - coverage run test_serverToClient.py

after_success:
#  - cd ../
  - 'coveralls'


# Checking to see if the QtGui module should be built...
# Checking to see if the QtHelp module should be built...
# Checking to see if the QtMultimedia module should be built...
# Checking to see if the QtNetwork module should be built...
# Checking to see if the QtDBus module should be built...
# Checking to see if the QtDeclarative module should be built...
# Checking to see if the QtScript module should be built...
# Checking to see if the QtScriptTools module should be built...
# Checking to see if the QtXml module should be built...
# Checking to see if the QtOpenGL module should be built...
# Checking to see if the QtSql module should be built...
# Checking to see if the QtSvg module should be built...
# Checking to see if the QtTest module should be built...
# Checking to see if the QtWebKit module should be built...
# Checking to see if the QtXmlPatterns module should be built...
# Checking to see if the phonon module should be built...
# Checking to see if the QtAssistant module should be built...
# Checking to see if the QtDesigner module should be built...
# Checking to see if the QAxContainer module should be built...
# Checking to see if the dbus support module should be built...