sudo: false

language: 'python'
cache: pip

branches:
  only:
    - master
    - development

python:
  - '2.7'

git:
  submodules: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - cd scripts
  - bash ./setup.sh -travisCI
  - cd ../tests
  - mkdir build
  - cd build
  - git clone https://github.com/PySide/pyside-setup.git pyside-setup
  - cd pyside-setup
  - python setup.py bdist_wheel --qmake=/usr/bin/qmake-qt4 --version=1.2.4
  - pip install dist/PySide-1.2.4*
  - cd ../..

script:
  - trial test_readDataFromFile
  - trial test_readDataFromTerminal
  - trial test_notifyMsgUsage
  - trial test_saveReceivedFrames
  - trial test_connectionDown
  - trial test_connectionEstablished
  - trial test_manageFrames
  - trial test_userinterfacesoperation
  - trial test_userinterfacesparameters
  - trial test_userinterfacesconnection
  - trial test_userinterfacedisconnection
  - trial test_userinterfaceclosewindow
#  - trial test_integrationConnection
  - trial test_configurationWindowOperation
  - coverage run test_readDataFromFile.py
  - coverage run test_readDataFromTerminal.py
  - coverage run test_notifyMsgUsage.py
  - coverage run test_saveReceivedFrames.py
  - coverage run test_connectionDown.py
  - coverage run test_connectionEstablished.py
  - coverage run test_manageFrames.py
  - coverage run test_userinterfacesoperation.py
  - coverage run test_userinterfacesparameters.py
  - coverage run test_userinterfacesconnection.py
  - coverage run test_userinterfacedisconnection.py
  - coverage run test_userinterfaceclosewindow.py
  - coverage run test_configurationWindowOperation.py

after_success:
  - coverage combine
#  - coverage report --omit '/home/travis/virtualenv/*'
  - coveralls --rcfile='/home/travis/build/satnet-project/generic-client/.coveragerc'