language: 'python'

branches:
  only:
    - master

python:
  - '2.7'

git:
  submodules: false

install:
  - pip install coveralls
  - cd scripts/
  - bash ./setup.sh -t
  - cd ../tests
  - pwd
  - cd ..
  - pwd

script:
  - coverage run test_clientToServer.py

after_success:
  - cd ../../
  - 'coveralls'
