language: 'python'

branches:
  only:
    - master

python:
  - '2.7'

git:
  submodules: false

before_install:
  - sudo apt-get install python-twisted
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd protocol
  - git checkout jrpc_if
  - cd ../ 

install:
  - pip install coveralls
  - cd scripts/
  - bash ./setup.sh -t
  - cd ../tests

script:
  - coverage run test_clientToServer.py
  - coverage run test_serverToClient.py

after_success:
  - cd ../../
  - pwd
  - 'coveralls'
