language: 'python'

branches:
  only:
    - master

python:
  - '2.7'

git:
  submodules: false

before_install:
  - sudo apt install build-essential
  - sudo apt install python-twisted 

install:
  - pip install coveralls
  - cd scripts/
  - bash ./setup.sh -t
  - cd ../tests
  - source /home/travis/virtualenv/bin/activate

script:
  - coverage run test_clientToServer.py

after_success:
  - cd ../../
  - 'coveralls'
