sudo: false

language: 'python'

branches:
  only:
    - master

python:
  - '2.7'

git:
  submodules: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - cd scripts
  - bash ./setup.sh -travisCI
  - cd ../tests
  - mkdir build && cd build
  - wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.zip
  - unzip sip-4.17.zip && cd sip-4.17
  - python configure.py --incdir="/home/travis/virtualenv/python2.7.9/lib/python2.7"
  - make
  - make install
  - cd ../ && rm -r -f sip-4.17
  - wget http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz
  - tar xvzf PyQt-x11-gpl-4.11.4.tar.gz
  - cd PyQt-x11-gpl-4.11.4
  - python ./configure.py --confirm-license --no-designer-plugin -q /usr/bin/qmake-qt4 -e QtGui -e QtCore -e QtTest
  - make
  - make install
  - cd ../ && rm -r -f PyQt-x11-gpl-4.11.4 && cd ../../

script:
  - cd tests
  - trial --coverage test_readDataFromFile
  - trial --coverage test_readDataFromTerminal
  - trial --coverage test_notifyMsgUsage
  - trial --coverage test_saveReceivedFrames
  - trial --coverage test_connectionDown
  - trial --coverage test_connectionEstablished
  - trial --coverage test_manageFrames
  - trial --coverage test_userInterface

after_success:
  - cd /home/travis/build/satnet-project/generic-client/tests/_trial_temp/coverage
  - ls
  - coverage combine
  - coverage report --omit '/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/*'
  - coveralls