sudo: false

language: 'python'

branches:
  only:
    - master

python:
  - '2.7'

git:
  submodules: false

before_install:
#  - sudo apt-get install python-twisted
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - cd protocol
  - git checkout jrpc_if
  - cd ../ 

install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
  - cd scripts/
  - bash ./setup.sh -travisCI
  - cd ../tests

  - echo "1"
  - pwd

  - mkdir build
  - pwd

  - cd build
  - pwd

  - pip install SIP --allow-unverified SIP --download="."
  - unzip sip*
  - echo "2"
  - pwd
  - cd sip*
  - python configure.py
  - make
  - make install

  - wget http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz
  - tar xvzf PyQt-x11-gpl-4.11.4.tar.gz
  - cd PyQt-x11-gpl-4.11.4 && python ./configure.py --confirm-license --no-designer-plugin -q /usr/bin/qmake-qt4
  - make
  - cp /sbin/ldconfig ../../bin/

# sudo ldconfig
  - make install
#  make install

script:
#  - python setup.py install
#  - nosetests --with-coverage --cover-erase --cover-package=ampauth --cover-package=client_amp
  - coverage run test_clientToServer.py
  - coverage run test_serverToClient.py

after_success:
#  - cd ../
  - 'coveralls'





#  cd ../ && rm -r -f sip*
#  cd ../ && rm -r -f PyQt*