language: 'python'
branches:
  only:
    - master
python:
  - '2.7'
# install:
#  - 'pip install -r requirements.txt'
#  - './scripts/setup.sh'
#before_script:
#  - "psql -c 'create database satnet_db;' -U postgres"
#  - 'python manage.py migrate'

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install:

script:
  - 'python tests/test_gs_interface.py test'
#  - 'coverage erase'
#  - 'coverage run manage.py test'
#after_script:
#  - 'coveralls'
